import { NextResponse, type NextRequest } from 'next/server'
import { createServerClient } from '@supabase/ssr'

export const runtime = "nodejs";

export async function GET(request: NextRequest) {
  const requestUrl = new URL(request.url)
  
  // We need an empty response to pass into createServerClient 
  // so that setAll can function, even though we won't return this response.
  // We will pass the cookies from this mock response to the final redirect response.
  const tempResponse = new NextResponse();

  const supabase = createServerClient(
    process.env.NEXT_PUBLIC_SUPABASE_URL!,
    process.env.NEXT_PUBLIC_SUPABASE_ANON_KEY!,
    {
      cookies: {
        getAll() {
          return request.cookies.getAll();
        },
        setAll(cookiesToSet) {
          cookiesToSet.forEach(({ name, value, options }) => {
            tempResponse.cookies.set(name, value, options);
          });
        },
      },
    }
  );

  const { data, error } = await supabase.auth.signInWithOAuth({
    provider: 'google',
    options: {
      redirectTo: `${requestUrl.origin}/auth/callback`, 
      queryParams: {
        access_type: "offline",
        prompt: "consent",
      },
    },
  })

  if (data?.url) {
    // This returns a standard 302 Found with the PKCE Set-Cookie headers.
    // Mobile browsers universally trust this pattern.
    const redirectResponse = NextResponse.redirect(data.url);
    
    // Copy the PKCE cookies generated by Supabase into our actual redirect response
    tempResponse.cookies.getAll().forEach(cookie => {
      redirectResponse.cookies.set(cookie.name, cookie.value, {
        path: '/',
        sameSite: 'lax',
        secure: process.env.NODE_ENV === 'production',
        maxAge: 60 * 60 * 24 * 7,
      });
    });

    return redirectResponse;
  }

  return NextResponse.redirect(`${requestUrl.origin}/login?error=outbound-failed`)
}
