import { NextResponse, type NextRequest } from 'next/server'
import { createServerClient } from '@supabase/ssr'

export const runtime = "nodejs";

export async function GET(request: NextRequest) {
  const requestUrl = new URL(request.url)
  const forwardedHost = request.headers.get("x-forwarded-host");
  const origin = forwardedHost ? `https://${forwardedHost}` : requestUrl.origin;
  
  // We need an empty response to pass into createServerClient 
  // so that setAll can function, even though we won't return this response.
  // We will pass the cookies from this mock response to the final redirect response.
  const tempResponse = new NextResponse();

  const supabase = createServerClient(
    process.env.NEXT_PUBLIC_SUPABASE_URL!,
    process.env.NEXT_PUBLIC_SUPABASE_ANON_KEY!,
    {
      cookies: {
        getAll() {
          return request.cookies.getAll();
        },
        setAll(cookiesToSet) {
          cookiesToSet.forEach(({ name, value, options }) => {
            tempResponse.cookies.set(name, value, options);
          });
        },
      },
    }
  );

  const { data, error } = await supabase.auth.signInWithOAuth({
    provider: 'google',
    options: {
      redirectTo: `${origin}/auth/callback`, 
      queryParams: {
        access_type: "offline",
        prompt: "consent",
      },
    },
  })

  if (data?.url) {
    // We cannot use a standard 302 Found redirect here.
    // Strict mobile browsers (ITP) will strip Set-Cookie headers from a 302 redirect 
    // that immediately crosses domains to a known tracker (Google).
    // Instead, we return a 200 OK HTML bouncer that forces the browser to paint,
    // save the PKCE cookie, and then navigate via client-side JavaScript.
    
    const html = `
      <!DOCTYPE html>
      <html>
        <head>
          <meta charset="utf-8" />
          <title>Connecting to Google...</title>
          <script>
            // Force a 500ms delay to ensure the PKCE cookie is committed to disk
            setTimeout(function() {
              window.location.replace("${data.url}");
            }, 500);
          </script>
        </head>
        <body style="background-color: #f3f4f6; display: flex; justify-content: center; align-items: center; height: 100vh; font-family: sans-serif;">
          <p>Connecting to Google securely...</p>
        </body>
      </html>
    `;

    const bouncerResponse = new NextResponse(html, {
      status: 200,
      headers: {
        'Content-Type': 'text/html; charset=utf-8',
      },
    });
    
    // Copy the PKCE cookies generated by Supabase into our actual 200 OK response
    tempResponse.cookies.getAll().forEach(cookie => {
      bouncerResponse.cookies.set(cookie.name, cookie.value, {
        path: '/',
        sameSite: 'lax',
        secure: process.env.NODE_ENV === 'production',
        maxAge: 60 * 60 * 24 * 7,
      });
    });

    return bouncerResponse;
  }

  return NextResponse.redirect(`${origin}/login?error=outbound-failed`)
}
