"use client";

import { useState, useTransition } from "react";
import Link from "next/link";
import { useRouter } from "next/navigation";
import {
  ArrowLeft,
  Sparkles,
  Flag,
  Loader2,
  Send,
  Check,
  Info,
} from "lucide-react";
import {
  createDoubtAnswer,
  reportContent,
  type DoubtPostDetail,
  type DoubtAnswer,
} from "@/app/actions/doubtBoard";

export default function DoubtPostClient({ post }: { post: DoubtPostDetail }) {
  const router = useRouter();
  // eslint-disable-next-line @typescript-eslint/no-unused-vars
  const [answers, setAnswers] = useState<DoubtAnswer[]>(post.answers);
  const [body, setBody] = useState("");
  const [error, setError] = useState<string | null>(null);
  const [isPending, startTransition] = useTransition();

  function submitAnswer() {
    setError(null);
    startTransition(async () => {
      const res = await createDoubtAnswer({ postId: post.id, body });
      if (res.success) {
        // Optimistically append; refresh to get server-canonical ordering/handle.
        setBody("");
        router.refresh();
      } else if (res.error === "SET_USERNAME_REQUIRED") {
        setError("Please set a username on the board before answering.");
      } else {
        setError(res.error);
      }
    });
  }

  return (
    <div className="flex flex-col gap-5 p-4 pt-6 pb-24 max-w-3xl mx-auto">
      <Link
        href={`/doubts?track=${post.examTrack}`}
        className="inline-flex items-center gap-1.5 text-sm font-semibold text-brand-ink-muted hover:text-brand-ink-inverse"
      >
        <ArrowLeft size={16} strokeWidth={2} aria-hidden="true" /> Back to {post.examTrack} board
      </Link>

      {/* Question */}
      <article className="rounded-2xl border border-brand-border-subtle bg-brand-bg-surface p-5">
        <div className="mb-2 flex items-center gap-2 text-xs text-brand-ink-muted">
          <span className="rounded-md bg-brand-accent-500/10 px-1.5 py-0.5 font-semibold text-brand-accent-500">
            {post.examTrack}
          </span>
          {post.topic && <span>· {post.topic}</span>}
          <span className="ml-auto">@{post.authorHandle}</span>
        </div>
        <h1 className="text-lg font-black text-brand-ink-inverse leading-snug">{post.title}</h1>
        <p className="mt-2 whitespace-pre-wrap text-sm text-brand-ink-muted">{post.body}</p>
        {!post.isOwnPost && (
          <ReportButton target={{ postId: post.id }} label="Report question" />
        )}
      </article>

      {/* Tejas AI draft — clearly labeled AI-generated */}
      {post.aiDraft && (
        <section
          aria-label="AI-drafted answer"
          className="rounded-2xl border border-violet-500/30 bg-violet-500/5 p-5"
        >
          <div className="mb-2 flex items-center gap-2">
            <span className="inline-flex items-center gap-1.5 rounded-lg bg-violet-500/15 px-2 py-1 text-xs font-bold text-violet-600">
              <Sparkles size={13} strokeWidth={2.2} aria-hidden="true" /> Tejas AI · Suggested answer
            </span>
          </div>
          <p className="whitespace-pre-wrap text-sm text-gray-700">{post.aiDraft}</p>
          <p className="mt-3 flex items-start gap-1.5 text-xs text-violet-600/80">
            <Info size={13} strokeWidth={2} className="mt-0.5 flex-shrink-0" aria-hidden="true" />
            This answer was generated by AI and may not be fully correct. Cross-check important
            facts, and see community answers below.
          </p>
        </section>
      )}

      {/* Community answers */}
      <section aria-label="Community answers" className="flex flex-col gap-3">
        <h2 className="text-sm font-bold uppercase tracking-wide text-brand-ink-muted">
          {answers.length} community {answers.length === 1 ? "answer" : "answers"}
        </h2>
        {answers.length === 0 ? (
          <p className="rounded-xl border border-dashed border-brand-border-subtle px-4 py-6 text-center text-sm text-brand-ink-muted">
            No community answers yet. Be the first to help.
          </p>
        ) : (
          <ul className="flex flex-col gap-3">
            {answers.map((a) => (
              <li
                key={a.id}
                className="rounded-2xl border border-brand-border-subtle bg-brand-bg-surface p-4"
              >
                <div className="mb-1.5 flex items-center gap-2 text-xs text-brand-ink-muted">
                  <span className="font-semibold">@{a.authorHandle}</span>
                  {a.isOwnAnswer && (
                    <span className="rounded bg-brand-accent-500/10 px-1.5 py-0.5 text-brand-accent-500">
                      You
                    </span>
                  )}
                </div>
                <p className="whitespace-pre-wrap text-sm text-brand-ink-inverse">{a.body}</p>
                {!a.isOwnAnswer && (
                  <ReportButton target={{ answerId: a.id }} label="Report answer" />
                )}
              </li>
            ))}
          </ul>
        )}
      </section>

      {/* Answer composer */}
      <section aria-label="Write an answer" className="rounded-2xl border border-brand-border-subtle bg-brand-bg-surface p-4">
        <h2 className="mb-2 text-sm font-bold text-brand-ink-inverse">Your answer</h2>
        {error && (
          <div role="alert" className="mb-3 rounded-xl bg-red-50 border border-red-200 px-3 py-2 text-sm text-red-700">
            {error}
          </div>
        )}
        <textarea
          value={body}
          onChange={(e) => setBody(e.target.value)}
          placeholder="Help this aspirant out (min 10 characters). Be respectful and accurate."
          rows={4}
          maxLength={3000}
          className="w-full resize-none rounded-xl border border-gray-200 px-4 py-2.5 text-sm text-gray-900 outline-none focus:border-brand-accent-500"
        />
        <div className="mt-2 flex items-center justify-between">
          <span className="text-xs text-brand-ink-muted">Public & moderated</span>
          <button
            type="button"
            onClick={submitAnswer}
            disabled={isPending || body.trim().length < 10}
            className="inline-flex items-center gap-2 rounded-xl bg-brand-accent-500 px-4 py-2 text-sm font-bold text-brand-accent-ink hover:bg-brand-accent-400 active:scale-95 disabled:opacity-50"
          >
            {isPending ? <Loader2 size={16} className="animate-spin" /> : <Send size={15} strokeWidth={2} />}
            Post answer
          </button>
        </div>
      </section>
    </div>
  );
}

// ─── Report button + modal ───────────────────────────────────────────────────

type ReportTarget = { postId: string } | { answerId: string };

function ReportButton({ target, label }: { target: ReportTarget; label: string }) {
  const [open, setOpen] = useState(false);
  const [done, setDone] = useState(false);
  const [reason, setReason] = useState<"spam" | "abuse" | "inappropriate" | "other">("abuse");
  const [details, setDetails] = useState("");
  const [error, setError] = useState<string | null>(null);
  const [isPending, startTransition] = useTransition();

  function submit() {
    setError(null);
    startTransition(async () => {
      const res = await reportContent({ ...target, reason, details });
      if (res.success) {
        setDone(true);
        setTimeout(() => setOpen(false), 1400);
      } else {
        setError(res.error);
      }
    });
  }

  return (
    <>
      <button
        type="button"
        onClick={() => setOpen(true)}
        className="mt-3 inline-flex items-center gap-1.5 text-xs font-semibold text-brand-ink-muted hover:text-red-500"
      >
        <Flag size={13} strokeWidth={1.9} aria-hidden="true" /> {label}
      </button>

      {open && (
        <div
          role="dialog"
          aria-modal="true"
          aria-label="Report content"
          className="fixed inset-0 z-[70] flex items-end justify-center bg-black/50 p-4 backdrop-blur-sm sm:items-center"
          onClick={() => setOpen(false)}
        >
          <div
            className="w-full max-w-md rounded-3xl bg-white p-6 shadow-2xl animate-fade-in"
            onClick={(e) => e.stopPropagation()}
          >
            {done ? (
              <div className="flex flex-col items-center gap-2 py-6 text-center">
                <div className="flex h-12 w-12 items-center justify-center rounded-full bg-emerald-100">
                  <Check size={24} strokeWidth={2.4} className="text-emerald-600" />
                </div>
                <p className="font-bold text-gray-900">Report submitted</p>
                <p className="text-sm text-gray-500">Our moderators will review it. Thank you.</p>
              </div>
            ) : (
              <>
                <h3 className="mb-1 text-lg font-black text-gray-900">Report this content</h3>
                <p className="mb-4 text-sm text-gray-500">
                  Reports go to our moderation team. Reporting is confidential.
                </p>
                {error && (
                  <div role="alert" className="mb-3 rounded-xl bg-red-50 border border-red-200 px-3 py-2 text-sm text-red-700">
                    {error}
                  </div>
                )}
                <div className="mb-4 flex flex-col gap-2">
                  {([
                    ["abuse", "Abuse or harassment"],
                    ["inappropriate", "Inappropriate / unsafe content"],
                    ["spam", "Spam or advertising"],
                    ["other", "Something else"],
                  ] as const).map(([value, text]) => (
                    <label
                      key={value}
                      className={`flex cursor-pointer items-center gap-2 rounded-xl border px-3 py-2.5 text-sm ${
                        reason === value
                          ? "border-brand-accent-500 bg-brand-accent-500/5 font-semibold text-gray-900"
                          : "border-gray-200 text-gray-600"
                      }`}
                    >
                      <input
                        type="radio"
                        name="report-reason"
                        value={value}
                        checked={reason === value}
                        onChange={() => setReason(value)}
                        className="accent-brand-accent-500"
                      />
                      {text}
                    </label>
                  ))}
                </div>
                <textarea
                  value={details}
                  onChange={(e) => setDetails(e.target.value)}
                  placeholder="Add any detail (optional)"
                  rows={2}
                  maxLength={500}
                  className="mb-4 w-full resize-none rounded-xl border border-gray-200 px-3 py-2 text-sm text-gray-900 outline-none focus:border-brand-accent-500"
                />
                <div className="flex gap-2">
                  <button
                    type="button"
                    onClick={() => setOpen(false)}
                    className="flex-1 rounded-xl border border-gray-200 px-4 py-2.5 text-sm font-semibold text-gray-600 hover:bg-gray-50"
                  >
                    Cancel
                  </button>
                  <button
                    type="button"
                    onClick={submit}
                    disabled={isPending}
                    className="flex-1 inline-flex items-center justify-center gap-2 rounded-xl bg-red-500 px-4 py-2.5 text-sm font-bold text-white hover:bg-red-600 active:scale-95 disabled:opacity-50"
                  >
                    {isPending ? <Loader2 size={16} className="animate-spin" /> : <Flag size={15} strokeWidth={2} />}
                    Submit report
                  </button>
                </div>
              </>
            )}
          </div>
        </div>
      )}
    </>
  );
}
