"use client";

import { useState, useTransition } from "react";
import Link from "next/link";
import { useRouter } from "next/navigation";
import {
  ArrowLeft,
  Sparkles,
  Flag,
  Loader2,
  Send,
  Check,
  Info,
  MessageCircle,
} from "lucide-react";
import ReactMarkdown from "react-markdown";
import {
  createDoubtAnswer,
  reportContent,
  type DoubtPostDetail,
  type DoubtAnswer,
} from "@/app/actions/doubtBoard";

export default function DoubtPostClient({ post }: { post: DoubtPostDetail }) {
  const router = useRouter();
  // eslint-disable-next-line @typescript-eslint/no-unused-vars
  const [answers, setAnswers] = useState<DoubtAnswer[]>(post.answers);
  const [body, setBody] = useState("");
  const [error, setError] = useState<string | null>(null);
  const [isPending, startTransition] = useTransition();

  function submitAnswer() {
    setError(null);
    if (body.trim().length < 10) {
      setError("Your answer must be at least 10 characters.");
      return;
    }
    startTransition(async () => {
      const res = await createDoubtAnswer({ postId: post.id, body });
      if (res.success) {
        // Optimistically append; refresh to get server-canonical ordering/handle.
        setBody("");
        router.refresh();
      } else if (res.error === "SET_USERNAME_REQUIRED") {
        setError("Please set a username on the board before answering.");
      } else {
        setError(res.error);
      }
    });
  }

  return (
    <div className="flex flex-col gap-5 p-4 pt-6 pb-24 max-w-3xl mx-auto">
      <Link
        href={`/doubts?track=${post.examTrack}`}
        className="inline-flex items-center gap-1.5 text-sm font-semibold text-brand-ink-muted hover:text-brand-ink-inverse"
      >
        <ArrowLeft size={16} strokeWidth={2} aria-hidden="true" /> Back to {post.examTrack} board
      </Link>

      {/* Question */}
      <article className="rounded-3xl border border-brand-border-subtle bg-brand-bg-surface p-6 shadow-sm relative overflow-hidden">
        <div className="absolute top-0 left-0 w-full h-1 bg-brand-accent-500"></div>
        <div className="mb-4 flex items-center gap-2 text-xs text-brand-ink-muted">
          <span className="rounded-lg bg-brand-accent-500/10 px-2.5 py-1 font-bold text-brand-accent-500 border border-brand-accent-500/20">
            {post.examTrack}
          </span>
          {post.topic && <span className="font-semibold">· {post.topic}</span>}
          <span className="ml-auto font-semibold">@{post.authorHandle}</span>
        </div>
        <h1 className="text-xl font-black text-brand-ink-inverse leading-tight mb-4">{post.title}</h1>
        <div className="text-sm text-brand-ink-muted leading-relaxed [&>p]:mb-3 last:[&>p]:mb-0 [&>strong]:font-bold [&>ul]:list-disc [&>ul]:ml-4 [&>ol]:list-decimal [&>ol]:ml-4">
          <ReactMarkdown>{post.body}</ReactMarkdown>
        </div>
        {!post.isOwnPost && (
          <div className="mt-4 pt-4 border-t border-brand-border-subtle/50">
            <ReportButton target={{ postId: post.id }} label="Report question" />
          </div>
        )}
      </article>

      {/* Tejas AI draft — clearly labeled AI-generated */}
      {post.aiDraft && (
        <section
          aria-label="AI-drafted answer"
          className="relative rounded-3xl border border-violet-200/60 bg-gradient-to-br from-violet-50/80 to-fuchsia-50/50 p-6 shadow-sm"
        >
          <div className="mb-4 flex items-center gap-2">
            <span className="inline-flex items-center gap-1.5 rounded-xl bg-white px-3 py-1.5 text-xs font-black text-violet-700 shadow-sm border border-violet-100">
              <Sparkles size={14} strokeWidth={2.5} aria-hidden="true" /> Tejas AI · Suggested answer
            </span>
          </div>
          <div className="text-sm text-gray-800 leading-relaxed [&>p]:mb-3 last:[&>p]:mb-0 [&>strong]:font-bold [&>strong]:text-gray-900 [&>code]:bg-violet-100 [&>code]:px-1.5 [&>code]:py-0.5 [&>code]:rounded-md [&>code]:text-violet-900 [&>ul]:list-disc [&>ul]:ml-4 [&>ul]:mb-3">
            <ReactMarkdown>{post.aiDraft}</ReactMarkdown>
          </div>
          <div className="mt-5 pt-4 border-t border-violet-200/50 flex items-start gap-2 text-xs text-violet-600/80 font-medium">
            <Info size={14} strokeWidth={2.2} className="mt-0.5 flex-shrink-0" aria-hidden="true" />
            <p>This answer was generated by AI and may not be fully correct. Cross-check important facts, and see community answers below.</p>
          </div>
        </section>
      )}

      {/* Community answers */}
      <section aria-label="Community answers" className="flex flex-col gap-4 mt-2">
        <h2 className="text-sm font-black uppercase tracking-wider text-brand-ink-muted px-1">
          {answers.length} community {answers.length === 1 ? "answer" : "answers"}
        </h2>
        {answers.length === 0 ? (
          <div className="rounded-3xl border border-dashed border-gray-300 bg-gray-50/50 px-6 py-12 text-center flex flex-col items-center justify-center gap-3">
            <div className="w-14 h-14 bg-gray-100 rounded-full flex items-center justify-center mb-1">
              <MessageCircle size={24} className="text-gray-400" strokeWidth={1.5} />
            </div>
            <p className="text-sm font-bold text-gray-700">No community answers yet</p>
            <p className="text-xs text-gray-500 font-medium">Be the first to help out this aspirant.</p>
          </div>
        ) : (
          <ul className="flex flex-col gap-4">
            {answers.map((a) => (
              <li
                key={a.id}
                className="rounded-3xl border border-gray-200 bg-white p-6 shadow-[0_2px_12px_rgba(0,0,0,0.03)]"
              >
                <div className="mb-3 flex items-center gap-2 text-xs text-gray-500">
                  <span className="font-bold text-gray-800">@{a.authorHandle}</span>
                  {a.isOwnAnswer && (
                    <span className="rounded-md bg-brand-accent-500/10 px-2 py-0.5 font-bold text-brand-accent-600 border border-brand-accent-500/20">
                      You
                    </span>
                  )}
                </div>
                <div className="text-sm text-gray-700 leading-relaxed [&>p]:mb-3 last:[&>p]:mb-0 [&>strong]:font-bold [&>ul]:list-disc [&>ul]:ml-4 [&>ol]:list-decimal [&>ol]:ml-4">
                  <ReactMarkdown>{a.body}</ReactMarkdown>
                </div>
                {!a.isOwnAnswer && (
                  <div className="mt-3 pt-3 border-t border-gray-100">
                    <ReportButton target={{ answerId: a.id }} label="Report answer" />
                  </div>
                )}
              </li>
            ))}
          </ul>
        )}
      </section>

      {/* Answer composer */}
      <section aria-label="Write an answer" className="rounded-3xl border border-gray-200 bg-white p-6 shadow-sm mt-2 relative overflow-hidden">
        <h2 className="mb-4 text-sm font-black text-gray-900 flex items-center gap-2">
          <Send size={16} className="text-brand-accent-500" strokeWidth={2.5} /> Your answer
        </h2>
        {error && (
          <div role="alert" className="mb-4 rounded-xl bg-red-50 border border-red-200 px-4 py-3 text-sm font-medium text-red-700 flex items-center gap-2">
            <Info size={16} className="text-red-500 flex-shrink-0" />
            {error}
          </div>
        )}
        <div className="relative">
          <textarea
            value={body}
            onChange={(e) => setBody(e.target.value)}
            placeholder="Help this aspirant out (min 10 characters). Markdown is supported."
            rows={5}
            maxLength={3000}
            className="w-full resize-none rounded-2xl border border-gray-200 bg-gray-50/50 px-5 py-4 text-sm text-gray-900 outline-none focus:border-brand-accent-500 focus:bg-white transition-colors"
          />
        </div>
        <div className="mt-4 flex flex-col sm:flex-row sm:items-center justify-between gap-4">
          <div className="flex flex-col">
            <span className="text-xs font-bold text-gray-700">Public & moderated</span>
            <span className="text-[11px] text-gray-500">You can use **bold**, *italic*, and lists.</span>
          </div>
          <button
            type="button"
            onClick={submitAnswer}
            disabled={isPending || body.trim().length < 10}
            className="inline-flex items-center justify-center gap-2 rounded-xl bg-brand-accent-500 px-6 py-3 text-sm font-bold text-white shadow-md shadow-brand-accent-500/20 hover:bg-brand-accent-400 active:scale-95 disabled:opacity-50 disabled:shadow-none transition-all"
          >
            {isPending ? <Loader2 size={18} className="animate-spin" /> : <Send size={16} strokeWidth={2.5} />}
            Post answer
          </button>
        </div>
      </section>
    </div>
  );
}

// ─── Report button + modal ───────────────────────────────────────────────────

type ReportTarget = { postId: string } | { answerId: string };

function ReportButton({ target, label }: { target: ReportTarget; label: string }) {
  const [open, setOpen] = useState(false);
  const [done, setDone] = useState(false);
  const [reason, setReason] = useState<"spam" | "abuse" | "inappropriate" | "other">("abuse");
  const [details, setDetails] = useState("");
  const [error, setError] = useState<string | null>(null);
  const [isPending, startTransition] = useTransition();

  function submit() {
    setError(null);
    startTransition(async () => {
      const res = await reportContent({ ...target, reason, details });
      if (res.success) {
        setDone(true);
        setTimeout(() => setOpen(false), 1400);
      } else {
        setError(res.error);
      }
    });
  }

  return (
    <>
      <button
        type="button"
        onClick={() => setOpen(true)}
        className="mt-1 inline-flex items-center gap-1.5 text-xs font-semibold text-brand-ink-muted hover:text-red-500 transition-colors"
      >
        <Flag size={13} strokeWidth={2.2} aria-hidden="true" /> {label}
      </button>

      {open && (
        <div
          role="dialog"
          aria-modal="true"
          aria-label="Report content"
          className="fixed inset-0 z-[70] flex items-end justify-center bg-black/50 p-4 backdrop-blur-sm sm:items-center"
          onClick={() => setOpen(false)}
        >
          <div
            className="w-full max-w-md rounded-3xl bg-white p-6 shadow-2xl animate-fade-in"
            onClick={(e) => e.stopPropagation()}
          >
            {done ? (
              <div className="flex flex-col items-center gap-2 py-6 text-center">
                <div className="flex h-12 w-12 items-center justify-center rounded-full bg-emerald-100">
                  <Check size={24} strokeWidth={2.4} className="text-emerald-600" />
                </div>
                <p className="font-bold text-gray-900">Report submitted</p>
                <p className="text-sm text-gray-500">Our moderators will review it. Thank you.</p>
              </div>
            ) : (
              <>
                <h3 className="mb-1 text-lg font-black text-gray-900">Report this content</h3>
                <p className="mb-4 text-sm text-gray-500">
                  Reports go to our moderation team. Reporting is confidential.
                </p>
                {error && (
                  <div role="alert" className="mb-3 rounded-xl bg-red-50 border border-red-200 px-3 py-2 text-sm text-red-700">
                    {error}
                  </div>
                )}
                <div className="mb-4 flex flex-col gap-2">
                  {([
                    ["abuse", "Abuse or harassment"],
                    ["inappropriate", "Inappropriate / unsafe content"],
                    ["spam", "Spam or advertising"],
                    ["other", "Something else"],
                  ] as const).map(([value, text]) => (
                    <label
                      key={value}
                      className={`flex cursor-pointer items-center gap-2 rounded-xl border px-3 py-2.5 text-sm ${
                        reason === value
                          ? "border-brand-accent-500 bg-brand-accent-500/5 font-semibold text-gray-900"
                          : "border-gray-200 text-gray-600"
                      }`}
                    >
                      <input
                        type="radio"
                        name="report-reason"
                        value={value}
                        checked={reason === value}
                        onChange={() => setReason(value)}
                        className="accent-brand-accent-500"
                      />
                      {text}
                    </label>
                  ))}
                </div>
                <textarea
                  value={details}
                  onChange={(e) => setDetails(e.target.value)}
                  placeholder="Add any detail (optional)"
                  rows={2}
                  maxLength={500}
                  className="mb-4 w-full resize-none rounded-xl border border-gray-200 px-3 py-2 text-sm text-gray-900 outline-none focus:border-brand-accent-500"
                />
                <div className="flex gap-2">
                  <button
                    type="button"
                    onClick={() => setOpen(false)}
                    className="flex-1 rounded-xl border border-gray-200 px-4 py-2.5 text-sm font-semibold text-gray-600 hover:bg-gray-50"
                  >
                    Cancel
                  </button>
                  <button
                    type="button"
                    onClick={submit}
                    disabled={isPending}
                    className="flex-1 inline-flex items-center justify-center gap-2 rounded-xl bg-red-500 px-4 py-2.5 text-sm font-bold text-white hover:bg-red-600 active:scale-95 disabled:opacity-50"
                  >
                    {isPending ? <Loader2 size={16} className="animate-spin" /> : <Flag size={15} strokeWidth={2} />}
                    Submit report
                  </button>
                </div>
              </>
            )}
          </div>
        </div>
      )}
    </>
  );
}
